In [3]:
import torch
from torch import nn

In [161]:
input = torch.randn(10, 1, 2)

In [162]:
# h0 = torch.randn(1, 1, 7)

In [163]:
input

tensor([[[ 0.4195,  0.9124]],

        [[ 0.7521, -0.1618]],

        [[-1.3284,  0.4656]],

        [[-0.7981, -0.6390]],

        [[-0.6949,  0.4304]],

        [[-1.6280, -0.6473]],

        [[-0.7926,  0.2752]],

        [[ 0.2850,  1.2107]],

        [[-1.0022, -1.0485]],

        [[-1.2310,  0.1264]]])

In [187]:
rnn = nn.RNN(input_size=2, hidden_size=2, num_layers=1)

In [188]:
output, hn = rnn(input)

In [189]:
output.size(), hn.size()

(torch.Size([10, 1, 2]), torch.Size([1, 1, 2]))

In [190]:
output, hn

(tensor([[[-0.7517,  0.1956]],
 
         [[-0.6041, -0.3723]],
 
         [[-0.8497, -0.0114]],
 
         [[-0.6614, -0.4263]],
 
         [[-0.7903, -0.0966]],
 
         [[-0.7371, -0.3588]],
 
         [[-0.7911, -0.1556]],
 
         [[-0.8837,  0.0417]],
 
         [[-0.5856, -0.5181]],
 
         [[-0.7547, -0.1284]]], grad_fn=<StackBackward>),
 tensor([[[-0.7547, -0.1284]]], grad_fn=<StackBackward>))

In [191]:
rnn.bias_ih_l0

Parameter containing:
tensor([-0.5808, -0.2812], requires_grad=True)

In [192]:
rnn.bias_hh_l0

Parameter containing:
tensor([-0.0303,  0.2291], requires_grad=True)

In [193]:
rnn.weight_ih_l0.size(), input.size()

(torch.Size([2, 2]), torch.Size([10, 1, 2]))

In [194]:
output.size()

torch.Size([10, 1, 2])

In [195]:
torch.mul(rnn.weight_ih_l0, input)

tensor([[[ 0.1073, -0.4730],
         [-0.0349,  0.2852]],

        [[ 0.1925,  0.0839],
         [-0.0627, -0.0506]],

        [[-0.3399, -0.2414],
         [ 0.1107,  0.1455]],

        [[-0.2042,  0.3312],
         [ 0.0665, -0.1997]],

        [[-0.1778, -0.2231],
         [ 0.0579,  0.1345]],

        [[-0.4166,  0.3355],
         [ 0.1356, -0.2023]],

        [[-0.2028, -0.1426],
         [ 0.0660,  0.0860]],

        [[ 0.0729, -0.6275],
         [-0.0237,  0.3784]],

        [[-0.2565,  0.5435],
         [ 0.0835, -0.3277]],

        [[-0.3150, -0.0655],
         [ 0.1026,  0.0395]]], grad_fn=<MulBackward0>)

In [196]:
torch.mul(rnn.weight_hh_l0, hn)

tensor([[[-0.2807,  0.0559],
         [-0.2393, -0.0083]]], grad_fn=<MulBackward0>)

In [144]:
hn.shape

torch.Size([2, 1, 3])

In [145]:
hn

tensor([[[ 0.0434,  0.3390, -0.6478]],

        [[-0.5405,  0.4320, -0.5389]]], grad_fn=<StackBackward>)

In [44]:
output.size(), hn.size()

(torch.Size([5, 3, 20]), torch.Size([2, 3, 20]))

In [45]:
rnn.weight_hh_l0.size()

torch.Size([20, 20])

In [46]:
rnn.weight_hh_l1.size()

torch.Size([20, 20])

In [48]:
hn.size()

torch.Size([2, 3, 20])

In [53]:
for item in rnn.named_parameters():
    print(item[0])

weight_ih_l0
weight_hh_l0
bias_ih_l0
bias_hh_l0
weight_ih_l1
weight_hh_l1
bias_ih_l1
bias_hh_l1
